name: Build and Publish Minecraft Witchcraft-and-Wizardry Distribution and Image

on:
  workflow_dispatch:

jobs:
  build-waw-distro:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '16'

    - name: Build latest waw distro
      run: |
        scripts/build-minecraft.sh --build-type witchcraft-and-wizardry

  build-waw-image:
    needs: 
    - build-waw-distro
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        build-args: |
          base_image=appbricks/mycs-node:dev
          mc_type=witchcraft-and-wizardry
          mc_version=latest
        push: true
        platforms: linux/amd64,linux/arm64
        tags: appbricks/minecraft-witchcraft-and-wizardry:dev

  build-prod-waw-image:
    needs: 
    - build-waw-distro
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        build-args: |
          base_image=appbricks/mycs-node:latest
          mc_type=witchcraft-and-wizardry
          mc_version=latest
        push: true
        platforms: linux/amd64,linux/arm64
        tags: appbricks/minecraft-witchcraft-and-wizardry:latest
