name: MyCS Minecraft Paper Distribution and Image

on:
  workflow_dispatch:

jobs:
  minecraft-version:
    runs-on: ubuntu-latest
    outputs: 
      version: ${{steps.get-version.outputs.version}}

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Get latest minecraft version
        id: get-version
        run: |
          version=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json \
            | jq -r '.["latest"]["release"]')

          echo "version=${version}" >> $GITHUB_OUTPUT

  build-paper-distro:
    needs: minecraft-version
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build latest paper distro
      run: |
        scripts/build-minecraft.sh --type paper --version ${{ needs.minecraft-version.outputs.version }}

  build-paper-image:
    needs: 
    - minecraft-version
    - build-paper-distro
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        build-args: |
          mc_type=paper
          mc_version=${{ needs.minecraft-version.outputs.version }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: appbricks/minecraft-paper:latest,appbricks/minecraft-paper:${{ needs.minecraft-version.outputs.version }}
